# Generated by Django 3.0.6 on 2020-12-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('numero_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuscripcionControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], max_length=10)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('email', models.ManyToManyField(to='suscripcion.SuscripcionUsuario')),
            ],
        ),
    ]
