# Generated by Django 3.0.6 on 2021-05-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], default='Publicado', max_length=12),
        ),
    ]
